<?php

declare(strict_types=1);

namespace PackageVersions;

/**
 * This class is generated by ocramius/package-versions, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions
{
    public const ROOT_PACKAGE_NAME = 'neos/neos-base-distribution';
    /**
     * Array of all available composer packages.
     * Dont read this array from your calling code, but use the \PackageVersions\Versions::getVersion() method instead.
     *
     * @var array<string, string>
     * @internal
     */
    public const VERSIONS          = array (
  'behat/transliterator' => 'v1.2.0@826ce7e9c2a6664c0d1f381cbb38b1fb80a7ee2c',
  'claudio/site-render' => 'dev-master@df596b04528a123630f2cb268a6521dc03d17e83',
  'claudio/ui-render' => 'dev-master@9c3dd324bd7727608de7d7b30c84e329bfeab4c2',
  'doctrine/annotations' => 'v1.7.0@fa4c4e861e809d6a1103bd620cce63ed91aedfeb',
  'doctrine/cache' => 'v1.8.0@d768d58baee9a4862ca783840eca1b9add7a7f57',
  'doctrine/collections' => 'v1.6.2@c5e0bc17b1620e97c968ac409acbff28b8b850be',
  'doctrine/common' => 'v2.10.0@30e33f60f64deec87df728c02b107f82cdafad9d',
  'doctrine/dbal' => 'v2.9.2@22800bd651c1d8d2a9719e2a3dc46d5108ebfcc9',
  'doctrine/event-manager' => 'v1.0.0@a520bc093a0170feeb6b14e9d83f3a14452e64b3',
  'doctrine/inflector' => 'v1.3.0@5527a48b7313d15261292c149e55e26eae771b0a',
  'doctrine/instantiator' => '1.2.0@a2c590166b2133a4633738648b6b064edae0814a',
  'doctrine/lexer' => '1.1.0@e17f069ede36f7534b95adec71910ed1b49c74ea',
  'doctrine/migrations' => 'v1.8.1@215438c0eef3e5f9b7da7d09c6b90756071b43e6',
  'doctrine/orm' => 'v2.6.3@434820973cadf2da2d66e7184be370084cc32ca8',
  'doctrine/persistence' => '1.1.1@3da7c9d125591ca83944f477e65ed3d7b4617c48',
  'doctrine/reflection' => 'v1.0.0@02538d3f95e88eb397a5f86274deb2c6175c2ab6',
  'flowpack/fusionbp' => 'dev-master@d4c9db10509753729283a34f8ca1bbf75722717e',
  'flowpack/neos-frontendlogin' => '3.0.3@a52b456f31a8a6aaaf639913da648c29d68377e0',
  'gedmo/doctrine-extensions' => 'v2.4.37@5dd471f656e46d815f063bf3f12c667649ec7ffb',
  'imagine/imagine' => '1.2.2@eec39b2092bc8008a92b8d63824476413dbe7511',
  'neos/cache' => '5.3.2@1b65dc7dea438aad9e452c8b34570b549eb729f1',
  'neos/composer-plugin' => '2.0.1@cd20e3c9b548127f4fa1e0f31662072bf82250d4',
  'neos/content-repository' => '4.3.3@b040881067e14b8ddb8b0dd900ddcdac64d0bd2d',
  'neos/demo' => '5.0.2@f6e90aece1e248e1b7c9e91b4568045a4e2e0475',
  'neos/diff' => '4.3.3@d917866be49f7532c1db02f23f6e327202d6fe01',
  'neos/eel' => '5.3.2@f44c966a1f212ab26bc7fbe4db8719055070069f',
  'neos/error-messages' => '5.3.2@9c8ea6b492b57521ba0cd6f97938e2071a664ff6',
  'neos/flow' => '5.3.2@e0238c9ba7ba5d61e4d08a8a313495cd1be6011d',
  'neos/flow-log' => '5.3.2@d97db81c24fdd05aab608ce088475a0df000a262',
  'neos/fluid-adaptor' => '5.3.2@bb762f006a76d707992d0da27321ed1a580ba635',
  'neos/form' => '4.2.1@3d4bccd33df9f2e4099312543d65b6198633c6c3',
  'neos/fusion' => '4.3.3@d78dfadc33b1510ef70aec58583d924d83ab9483',
  'neos/fusion-afx' => 'v1.2.0@b7574d371128251000d4e7499d9910f05558bb01',
  'neos/imagine' => '3.1.1@85991dcccebc311ccf17babb7f75518e8b05550a',
  'neos/kickstarter' => '5.3.2@15590009d631729a43db6ed299967693e62ad5d8',
  'neos/media' => '4.3.3@300b09d769f4d31b8a9577c0822e7272c6646a09',
  'neos/media-browser' => '4.3.3@e653174cea976aadc29845923df655bf43f59d3f',
  'neos/neos' => '4.3.3@4f1ff6a8567e59cd7b3645298b40537d9c58684a',
  'neos/neos-ui' => '3.8.1@50093e6f024a9176be559844848d3b264ef4c834',
  'neos/neos-ui-compiled' => '3.8.1@b27b1713c601027f86356fee8a0edaa501576784',
  'neos/nodetypes' => '4.3.3@3e2d1735e44b5755d8883a7d25e01b552b604d4a',
  'neos/nodetypes-assetlist' => '4.3.3@0cc5441deafa8db35312a2e9725c77852916bb2b',
  'neos/nodetypes-basemixins' => '4.3.3@2860aebbafda9492807c8bb93cf40d5523586268',
  'neos/nodetypes-columnlayouts' => '4.3.3@b7b2c3944a2aff918436f1601fb216f77bc04aa4',
  'neos/nodetypes-contentreferences' => '4.3.3@7d4797e595d544d505f8259a953ddf043326f4e6',
  'neos/nodetypes-form' => '4.3.3@8630845abed5e68972a8351dfc0e560bb6692fd7',
  'neos/nodetypes-html' => '4.3.3@c5fd79c62b93eb44a57e9fa68e4f00eba0d253c1',
  'neos/nodetypes-navigation' => '4.3.3@061609e00dd317f03a47e8e3fd51d842bf42aa1f',
  'neos/party' => '5.0.1@c6d7b17c9aedcb3fe5dcd8ee0a0980d83986516c',
  'neos/redirecthandler' => '2.0.1@351effbe2d184e82cc1dc65a5e409d092ba56194',
  'neos/redirecthandler-databasestorage' => '3.0.0@89afaf857bb79286127544e659fa00d5124e5499',
  'neos/redirecthandler-neosadapter' => '3.0.1@ab4a902e893d1282bd78a3da2ad9e9cd0fb73844',
  'neos/seo' => '3.0.4@a7a99d15a8b94267b6f4726b3ed27f3786ea36e8',
  'neos/setup' => 'dev-master@8c569a5c2873e116e9acf8a93e008641c1235138',
  'neos/site-kickstarter' => '4.3.3@9457a1d2c6a37abe46d84b270abf072eabe38d81',
  'neos/twitter-bootstrap' => '3.0.4@f1da794467a79d9a9be113749a2c9d38cf8c1eec',
  'neos/utility-arrays' => '5.3.2@13e13742cb9b2073f37a825e109615824bc7ecd6',
  'neos/utility-files' => '5.3.2@b9da4cd16e03063e3b6bee5f0bb64a3ce3a5022d',
  'neos/utility-lock' => '5.3.2@b9a59db6cf3d1876aeed88fca7df44d7ccf5c8f1',
  'neos/utility-mediatypes' => '5.3.2@40344416b38aad4c9cb901890eeadf6a29d75731',
  'neos/utility-objecthandling' => '5.3.2@a09565510ea553cd458521f8b074325a20a1c8fd',
  'neos/utility-opcodecache' => '5.3.2@e3a7536809c90dedb93bd8e6e98184728aeb9daa',
  'neos/utility-pdo' => '5.3.2@3091215c460563347f53ac5fb39349ab663acc0f',
  'neos/utility-schema' => '5.3.2@9338031a95b7b7c4c9cde49713f3f8b6aaf728e6',
  'neos/utility-unicode' => '5.3.2@7b5e40bc2a8530068d2a0ec0058719202689d465',
  'ocramius/package-versions' => '1.5.1@1d32342b8c1eb27353c8887c366147b4c2da673c',
  'ocramius/proxy-manager' => '2.2.3@4d154742e31c35137d5374c998e8f86b54db2e2f',
  'packagefactory/afx' => 'v3.0.0@52e11d86c75c74cc34ed195103cf697dae1f82ad',
  'paragonie/random_compat' => 'v9.99.99@84b4dfb120c6f9b4ff7b3685f9b8f1aa365a0c95',
  'psr/cache' => '1.0.1@d11b50ad223250cf17b86e38383413f5a6764bf8',
  'psr/container' => '1.0.0@b7ce3b176482dbbc1245ebf52b181af44c2cf55f',
  'psr/http-message' => '1.0.1@f6561bf28d520154e4b0ec72be95418abe6d9363',
  'psr/log' => '1.1.0@6c001f1daafa3a3ac1d8ff69ee4db8e799a654dd',
  'psr/simple-cache' => '1.0.1@408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
  'ramsey/uuid' => '3.8.0@d09ea80159c1929d75b3f9c60504d613aeb4a1e3',
  'symfony/console' => 'v4.3.3@8b0ae5742ce9aaa8b0075665862c1ca397d1c1d9',
  'symfony/dom-crawler' => 'v4.3.3@291397232a2eefb3347eaab9170409981eaad0e2',
  'symfony/polyfill-ctype' => 'v1.12.0@550ebaac289296ce228a706d0867afc34687e3f4',
  'symfony/polyfill-mbstring' => 'v1.12.0@b42a2f66e8f1b15ccf25652c3424265923eb4f17',
  'symfony/polyfill-php73' => 'v1.12.0@2ceb49eaccb9352bff54d22570276bb75ba4a188',
  'symfony/service-contracts' => 'v1.1.5@f391a00de78ec7ec8cf5cdcdae59ec7b883edb8d',
  'symfony/yaml' => 'v4.3.3@34d29c2acd1ad65688f58452fd48a46bd996d5a6',
  'typo3fluid/fluid' => '2.6.1@9ef6a8ffff2e812025fc0701b4ce72eea6911a3d',
  'zendframework/zend-code' => '3.3.1@c21db169075c6ec4b342149f446e7b7b724f95eb',
  'zendframework/zend-eventmanager' => '3.2.1@a5e2583a211f73604691586b8406ff7296a946dd',
  'mikey179/vfsstream' => 'v1.6.7@2b544ac3a21bcc4dde5d90c4ae8d06f4319055fb',
  'myclabs/deep-copy' => '1.9.3@007c053ae6f31bba39dfa19a7726f56e9763bbea',
  'neos/behat' => 'dev-master@33c186ac981a7776cecf60b89f3c983c794b849b',
  'neos/buildessentials' => 'dev-master@a7ee07376d6243acf2813e4ce0ea2d35ff7cfa84',
  'phar-io/manifest' => '1.0.3@7761fcacf03b4d4f16e7ccb606d4879ca431fcf4',
  'phar-io/version' => '2.0.1@45a2ec53a73c70ce41d55cedef9063630abaf1b6',
  'phpdocumentor/reflection-common' => '1.0.1@21bdeb5f65d7ebf9f43b1b25d404f87deab5bfb6',
  'phpdocumentor/reflection-docblock' => '4.3.1@bdd9f737ebc2a01c06ea7ff4308ec6697db9b53c',
  'phpdocumentor/type-resolver' => '0.4.0@9c977708995954784726e25d0cd1dddf4e65b0f7',
  'phpspec/prophecy' => '1.8.1@1927e75f4ed19131ec9bcc3b002e07fb1173ee76',
  'phpunit/php-code-coverage' => '6.1.4@807e6013b00af69b6c5d9ceb4282d0393dbb9d8d',
  'phpunit/php-file-iterator' => '2.0.2@050bedf145a257b1ff02746c31894800e5122946',
  'phpunit/php-text-template' => '1.2.1@31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
  'phpunit/php-timer' => '2.1.2@1038454804406b0b5f5f520358e78c1c2f71501e',
  'phpunit/php-token-stream' => '3.1.0@e899757bb3df5ff6e95089132f32cd59aac2220a',
  'phpunit/phpunit' => '7.5.14@2834789aeb9ac182ad69bfdf9ae91856a59945ff',
  'sebastian/code-unit-reverse-lookup' => '1.0.1@4419fcdb5eabb9caa61a27c7a1db532a6b55dd18',
  'sebastian/comparator' => '3.0.2@5de4fc177adf9bce8df98d8d141a7559d7ccf6da',
  'sebastian/diff' => '3.0.2@720fcc7e9b5cf384ea68d9d930d480907a0c1a29',
  'sebastian/environment' => '4.2.2@f2a2c8e1c97c11ace607a7a667d73d47c19fe404',
  'sebastian/exporter' => '3.1.1@06a9a5947f47b3029d76118eb5c22802e5869687',
  'sebastian/global-state' => '2.0.0@e8ba02eed7bbbb9e59e43dedd3dddeff4a56b0c4',
  'sebastian/object-enumerator' => '3.0.3@7cfd9e65d11ffb5af41198476395774d4c8a84c5',
  'sebastian/object-reflector' => '1.1.1@773f97c67f28de00d397be301821b06708fca0be',
  'sebastian/recursion-context' => '3.0.0@5b0cd723502bac3b006cbf3dbf7a1e3fcefe4fa8',
  'sebastian/resource-operations' => '2.0.1@4d7a795d35b889bf80a0cc04e08d77cedfa917a9',
  'sebastian/version' => '2.0.1@99732be0ddb3361e16ad77b68ba41efc8e979019',
  'symfony/css-selector' => 'v2.8.50@7b1692e418d7ccac24c373528453bc90e42797de',
  'theseer/tokenizer' => '1.1.3@11336f6f84e16a720dae9d8e6ed5019efa85a0f9',
  'webmozart/assert' => '1.4.0@83e253c8e0be5b0257b881e1827274667c5c17a9',
  'neos/neos-base-distribution' => 'No version set (parsed as 1.0.0)@',
);

    private function __construct()
    {
    }

    /**
     * @throws \OutOfBoundsException If a version cannot be located.
     *
     * @psalm-param key-of<self::VERSIONS> $packageName
     */
    public static function getVersion(string $packageName) : string
    {
        if (isset(self::VERSIONS[$packageName])) {
            return self::VERSIONS[$packageName];
        }

        throw new \OutOfBoundsException(
            'Required package "' . $packageName . '" is not installed: check your ./vendor/composer/installed.json and/or ./composer.lock files'
        );
    }
}
