<?php 
namespace Neos\Neos\Utility;

/*
 * This file is part of the Neos.Neos package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */


/**
 * A collection of helper methods for the Neos backend assets
 */
class BackendAssetsUtility_Original
{
    /**
     * @var array
     */
    protected $settings;

    /**
     * @param array $settings
     * @return void
     */
    public function injectSettings(array $settings)
    {
        $this->settings = $settings;
    }

    /**
     * Returns true if the minified Neos JavaScript sources should be loaded, false otherwise.
     *
     * @return boolean
     */
    public function shouldLoadMinifiedJavascript()
    {
        if (isset($this->settings['userInterface']['loadMinifiedJavaScript'])) {
            return $this->settings['userInterface']['loadMinifiedJavaScript'];
        } elseif (isset($this->settings['userInterface']['loadMinifiedJavascript'])) {
            return $this->settings['userInterface']['loadMinifiedJavascript'];
        }
        return true;
    }

    /**
     * Returns a shortened md5 of the built JavaScript file
     *
     * @return string
     */
    public function getJavascriptBuiltVersion()
    {
        return substr(md5_file('resource://Neos.Neos/Public/JavaScript/ContentModule-built.js'), 0, 12);
    }

    /**
     * Returns a shortened md5 of the built CSS file
     *
     * @return string
     */
    public function getCssBuiltVersion()
    {
        return substr(md5_file('resource://Neos.Neos/Public/Styles/Includes-built.css'), 0, 12);
    }
}

#
# Start of Flow generated Proxy code
#
namespace Neos\Neos\Utility;

use Doctrine\ORM\Mapping as ORM;
use Neos\Flow\Annotations as Flow;

/**
 * A collection of helper methods for the Neos backend assets
 */
class BackendAssetsUtility extends BackendAssetsUtility_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait, \Neos\Flow\ObjectManagement\DependencyInjection\PropertyInjectionTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __construct()
    {
        if ('Neos\Neos\Utility\BackendAssetsUtility' === get_class($this)) {
            $this->Flow_Proxy_injectProperties();
        }
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();

        $transientProperties = array (
);
        $propertyVarTags = array (
  'settings' => 'array',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
        $this->Flow_Proxy_injectProperties();
    }

    /**
     * Autogenerated Proxy Method
     */
    private function Flow_Proxy_injectProperties()
    {
        $this->injectSettings(\Neos\Flow\Core\Bootstrap::$staticObjectManager->get(\Neos\Flow\Configuration\ConfigurationManager::class)->getConfiguration('Settings', 'Neos.Neos'));
        $this->Flow_Injected_Properties = array (
  0 => 'settings',
);
    }
}
# PathAndFilename: /var/www/html/neos/Packages/Application/Neos.Neos/Classes/Utility/BackendAssetsUtility.php
#