<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'org\\bovigo\\vfs\\' => array($vendorDir . '/mikey179/vfsstream/src/main/php'),
    'ProxyManager\\' => array($vendorDir . '/ocramius/proxy-manager/src'),
    'Neos\\Neos\\Ui\\Compiled' => array($baseDir . '/Packages/Application/Neos.Neos.Ui.Compiled/Classes'),
    'Flowpack\\Neos\\FrontendLogin' => array($baseDir . '/Packages/Plugins/Flowpack.Neos.FrontendLogin/Classes'),
    'Behat\\Transliterator' => array($vendorDir . '/behat/transliterator/src'),
);
