<?php

namespace Neos\Flow\Persistence\Doctrine\Proxies\__CG__\Neos\ContentRepository\Domain\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Workspace extends \Neos\ContentRepository\Domain\Model\Workspace implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * {@inheritDoc}
     * @return array
     */
    public function __sleep()
    {
        $properties = array_merge(['__isInitialized__'], parent::__sleep());

        if ($this->__isInitialized__) {
            $properties = array_diff($properties, array_keys($this->__getLazyProperties()));
        }

        return $properties;
    }

    /**
     * {@inheritDoc}
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Workspace $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
        parent::__wakeup();
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function publish(\Neos\ContentRepository\Domain\Model\Workspace $targetWorkspace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'publish', [$targetWorkspace]);

        return parent::publish($targetWorkspace);
    }

    /**
     * {@inheritDoc}
     */
    public function publishNodes(array $nodes, \Neos\ContentRepository\Domain\Model\Workspace $targetWorkspace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'publishNodes', [$nodes, $targetWorkspace]);

        return parent::publishNodes($nodes, $targetWorkspace);
    }

    /**
     * {@inheritDoc}
     */
    public function publishNode(\Neos\ContentRepository\Domain\Model\NodeInterface $nodeToPublish, \Neos\ContentRepository\Domain\Model\Workspace $targetWorkspace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'publishNode', [$nodeToPublish, $targetWorkspace]);

        return parent::publishNode($nodeToPublish, $targetWorkspace);
    }

    /**
     * {@inheritDoc}
     */
    public function initializeObject($initializationCause)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'initializeObject', [$initializationCause]);

        return parent::initializeObject($initializationCause);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getName();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', []);

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', [$user]);

        return parent::setOwner($user);
    }

    /**
     * {@inheritDoc}
     */
    public function isPersonalWorkspace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPersonalWorkspace', []);

        return parent::isPersonalWorkspace();
    }

    /**
     * {@inheritDoc}
     */
    public function isPrivateWorkspace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPrivateWorkspace', []);

        return parent::isPrivateWorkspace();
    }

    /**
     * {@inheritDoc}
     */
    public function isInternalWorkspace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isInternalWorkspace', []);

        return parent::isInternalWorkspace();
    }

    /**
     * {@inheritDoc}
     */
    public function isPublicWorkspace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPublicWorkspace', []);

        return parent::isPublicWorkspace();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaseWorkspace(\Neos\ContentRepository\Domain\Model\Workspace $baseWorkspace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaseWorkspace', [$baseWorkspace]);

        return parent::setBaseWorkspace($baseWorkspace);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseWorkspace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaseWorkspace', []);

        return parent::getBaseWorkspace();
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseWorkspaces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaseWorkspaces', []);

        return parent::getBaseWorkspaces();
    }

    /**
     * {@inheritDoc}
     */
    public function getRootNodeData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRootNodeData', []);

        return parent::getRootNodeData();
    }

    /**
     * {@inheritDoc}
     */
    public function getNodeCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNodeCount', []);

        return parent::getNodeCount();
    }

    /**
     * {@inheritDoc}
     */
    public function Flow_Aop_Proxy_invokeJoinPoint(\Neos\Flow\Aop\JoinPointInterface $joinPoint)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'Flow_Aop_Proxy_invokeJoinPoint', [$joinPoint]);

        return parent::Flow_Aop_Proxy_invokeJoinPoint($joinPoint);
    }

}
